version: 2

build:
   os: "ubuntu-22.04"
   tools:
      python: "3.10"
   commands:
      #
      # xrst
      - pip install xrst
      - pip uninstall -y xrst
      - pip install --index-url https://test.pypi.org/simple/ xrst
      - xrst --version
      #
      # build/html
      # The xsrst html_directory for this configuration is build/html.
      # Build the default (user_guide) and app (appendix) groups.
      - xrst
         --page_source
         --html_theme furo
         --group_list default
         --index_page_name cmpad
         --suppress_spell_warnings
      #
      # _readthedocs/html
      # The directory that Read the Docs uploads when commands is used.
      - mkdir _readthedocs
      - rm -r build/html/.doctrees
      - cp -r build/html _readthedocs/html
