# SPDX-License-Identifier: EPL-2.0 OR GPL-2.0-or-later
# SPDX-FileCopyrightText: Bradley M. Bell <bradbell@seanet.com>
# SPDX-FileContributor: 2023 Bradley M. Bell
# ---------------------------------------------------------------------------
[project_name]
data = 'cmpad'

[root_file]
default  = 'cmpad.xrst'

# If running an old verison of xrst that does not support heading,
# comment out the lines from [heading] to overline =.
[heading]
#   level         0,     1,     2,     3,     4,
character = [   '#',   '*',   '=',   '-',   '.',  ]
overline  = [ false, false, false, false, false,  ]

[input_files]
data = [
   [ 'git', 'ls-files' ]
]

[html_theme_options.sphinx_book_theme]
show_toc_level = 4

[html_theme_options.sphinx_rtd_theme]
navigation_depth = -1
titles_only      = true

[include_all]
rst_epilog = ''
rst_prolog = '''
.. |space| unicode:: 0xA0
.. |tab| replace:: |space| |space| |space|
'''
latex_macro = [
   '\newcommand{\B}[1]{ {\bf #1} }' ,
   '\newcommand{\R}[1]{ {\rm #1} }' ,
]

[project_dictionary]
data = [
   # project name
   '''
      cmpad
   ''',
   # package names
   '''
      adolc
      autodiff
      autograd
      cppad
      cppadcg
      fastad
      jit
      pytorch
      sacado
   ''',
   # option field names
   '''
      arg
   ''',
   # file extensions
   '''
      csv
      hpp
      cpp
      py
      rst
      sh
   ''',
   # language keywords
   '''
      bool
      namespace
   ''',
   # abbreviations used by this package
   '''
      algo
      det
      min
      ok
   ''',
   # words that do not begin with backslash and used in latex
   '''
      eqnarray
   ''',
   # valid words not in some dictionaries
   '''
      factorial
   ''',
]

[not_in_index]
data = []
